[[fixeddata]]
name = "case-1"
data = [
    { A = [52] },
    { Q = 52 },
    { A = [47] },
    '??',
    { A = [3] },
    { Q = 3 },
    { A = [35] },
    { A = [24] },
    { Q = 24 },
    { A = [44] },
    { A = [66] },
    { A = [38] },
    { A = [30] },
    { A = [28] },
    { R = [19, 19] },
    '??',
    { R = [35, +inf] },
    { R = [34, +inf] },
    { R = [36, +inf] },
    { R = [34, 66] },
    { R = [36, 67] },
    '??',
    { R = [34, 45] },
    '??',
    { Q = 28 },
    { D = 24 },
    { D = 44 },
    { D = 66 },
    { D = 38 },
    { D = 52 },
    { D = 47 },
    { D = 3 },
    { R = [-inf, +inf] },
    { D = 35 },
    { D = 30 },
    '??',
    { D = 28 },
    { R = [-inf, +inf] },
    '??'
]
