[[fixeddata]]
name = "case-6"
data = [
    { A = [15] },
    { A = [88] },
    { D = 15 },
    { A = [95] },
    { A = [57] },
    { A = [5] },
    { A = [89] },
    { A = [53] },
    { A = [27] },
    { A = [96] },
    { A = [48] },
    { A = [4] },
    { D = 96 },
    { A = [2] },
    { D = 89 },
    { A = [10] },
    { A = [11] },
    { A = [54] },
    { D = 4 },
    { D = 5 },
    { D = 54 },
    { A = [55] },
    '??',
    { D = 2 },
    { D = 27 },
    { D = 55 },
    { A = [39] },
    { D = 54 },
    { D = 53 },
    { D = 10 },
    { D = 88 },
    { D = 39 },
    { D = 23 },
    { D = 11 },
    '??'
]

[[fixeddata]]
name = "case-5"
data = [
    { A = [92] },
    { A = [17] },
    { A = [59] },
    { A = [36] },
    { A = [99] },
    { A = [99] },
    { D = 48 },
    { A = [12] },
    { A = [64] },
    { A = [53] },
    { A = [3] },
    { A = [23] },
    { A = [2] },
    { D = 3 },
    { D = 64 },
    { D = 17 },
    { D = 2 },
    { A = [35] },
    { D = 73 },
    { D = 23 },
    { D = 26 },
    { A = [72] },
    { A = [99, 48] },
    { D = 99 },
    { D = 36 },
    { D = 72 },
    '??',
    { D = 35 },
    '??'
]

[[fixeddata]]
name = "case-4"
data = [
    { A = [22] },
    { A = [50] },
    { A = [3] },
    { A = [85] },
    { A = [89] },
    { A = [23] },
    { A = [73] },
    { D = 85 },
    { D = 3 },
    { A = [46] },
    { D = 89 },
    { A = [41] },
    { D = 22 },
    { D = 23 },
    { A = [98] },
    { D = 73 },
    { D = 46 },
    { D = 98 },
    { D = 57 },
    '??',
    { D = 41 },
    { D = 83 },
    '??'
]

[[fixeddata]]
name = "case-validate-empty"
data = [
    { A = [52] },
    '??',
    { D = 52 },
    '??',
]

[[fixeddata]]
name = "case-1"
data = [
    { A = [52] },
    { Q = 52 },
    { A = [47] },
    '??',
    { A = [3] },
    { Q = 3 },
    { A = [35] },
    { A = [24] },
    { Q = 24 },
    { A = [44] },
    { A = [66] },
    { A = [38] },
    { A = [30] },
    { A = [28] },
    '??',
    { Q = 28 },
    { D = 24 },
    { D = 44 },
    { D = 66 },
    { D = 38 },
    { D = 52 },
    { D = 47 },
    { D = 3 },
    { D = 35 },
    { D = 30 },
    '??',
    { D = 28 },
    '??'
]

[[fixeddata]]
name = "case-2"
data = [
    { A = [25] },
    { A = [62] },
    { A = [6] },
    { A = [2] },
    { A = [45] },
    { A = [55] },
    { A = [51] },
    { D = 45 },
    { D = 55 },
    { D = 51 },
    { D = 25 },
    { D = 11 },
    '??',
]

[[fixeddata]]
name = "case-3"
data = [
    { A = [22] },
    { A = [18] },
    { A = [12] },
    { A = [58] },
    { A = [20] },
    { A = [42] },
    { A = [34] },
    { A = [32] },
    { A = [13] },
    { A = [45] },
    { A = [10] },
    { A = [46] },
    '??',
    { A = [53] },
    { A = [0] },
    { A = [27] },
    '??',
    { D = 34 },
    { D = 13 },
    { D = 18 },
    { D = 0 },
    '??',
    { D = 46 },
    { D = 42 },
    { D = 22 },
    '??',
]
