[package]
name = "m6-coll-persistent"
version = "0.1.5"
edition = "2024"

[dependencies]
common = { package = "m6-common", path = "../common" }
coll = { package = "m6-coll", path = "../coll" }

[package.metadata.workspaces]
independent = true
