[package]
name = "m6-coll-persistent"
version = "0.1.0"
edition = "2021"

[dependencies]
m6arr = { path = "../../m6coll/m6arr" }


common = { package = "m6-common", path = "../common" }
coll = { package = "m6-coll", path = "../coll" }
