[package]
name = "minghu6"
version = "0.1.0"
authors = ["minghu6 <a19678zy@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chardet = "^0.2"
encoding = "^0.2"
maplit = "^1.0.2"
rand = "^0.7"
num-format = "^0.4.0"
twox-hash = "^1.5.0"
bit-vec = "^0.6.2"
num_cpus = "1.0"
itertools = "0.10.*"
either = "1.6.1"
serde = { version = "1.*", features = ["derive"] }
serde_json = "1.0"
archery = "0.4"
derive-where = "1.0.0-rc.1"
lazy_static = "1.4.0"
m6coll = { path = "../m6coll" }
sorted-vec = "0.7.0"


[dependencies.uuid]
version = "0.8.2"
features = [
    "v4"
]


[dependencies.proc_macros]
package = "m6-proc-macros"
path = "proc_macros"


[workspace]
members = ["proc_macros", "tools/*"]


[profile.bench]
debug = true
