[package]
name = "minghu6"
version = "0.1.0"
authors = ["minghu6 <a19678zy@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chardet = "^0.2"
encoding = "^0.2"
maplit = "^1.0.2"
rand = "^0.7"
num-format = "^0.4.0"
twox-hash = "^1.5.0"
