[package]
name = "m6-proc-macros"
version = "0.1.1"
edition = "2018"


[dependencies]
proc-macro2 = "^1.0"
quote = "^1.0"
syn = "^1.0"
uuid = { version = "0.8", features = ["v4"] }

[lib]
proc-macro = true

[package.metadata.workspaces]
independent = true
