
test-mst:
	cargo test test_mst -- --nocapture

test-bcc:
	cargo test bcc -- --nocapture

test-scc:
	cargo test scc -- --nocapture

test-sp:
	cargo test sp -- --nocapture

test-sp-spfa:
	cargo test spfa -- --nocapture

test-sp-dijkstra:
	cargo test sp_randomdata_pw -- --nocapture


