[package]
name = "bp_remove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
minghu6 = { path = "../../" }
lazy_static = "1.4.0"
rand = "^0.7"

[profile.release]
debug = true
