[package]
name = "m6-common"
version = "0.1.9"
edition = "2021"

[dependencies]
extern_rand = { package = "rand", version = "^0.8" }
itertools = "=0.10.1"

proc_macros = { package = "m6-proc-macros", path = "../proc_macros" }

[package.metadata.workspaces]
independent = true
